Maj des tests d'intégration
IGNF/road2 pull request #13
Opened 2023-01-10 11:20 UTC by lgrd

2023-01-10 14:58 UTC, jmkerloch requested changes
@lgrd could you rebase to develop ? I have an issue with docker-compose build that seems to be corrected.

In general it would be better if all branches are rebased from develop before merging with PR.

2023-01-10 14:58 UTC, jmkerloch commented on test/functional/readme.md
> +- exécuter la commande `npm run rtest` via docker-compose.
It should be npm run ctest no ?
```suggestion
- exécuter la commande `npm run ctest` via docker-compose. 
```

2023-01-10 16:01 UTC, jmkerloch commented
@lgrd I rebased locally and I have an error when launching itest. Do you have any idea of what could be wrong ? Maybe the test are not valid after a rebase.

```
> road2@2.0.0-DEVELOP itest
> nyc mocha --recursive './test/integration/mocha/**/*.js'
TypeError: Cannot read properties of undefined (reading 'schema')
    at new pgrSource (/home/docker/app/src/js/sources/pgrSource.js:21:69)
    at Suite.<anonymous> (/home/docker/app/test/integration/mocha/sources/integrationPgrSource.js:67:16)
```

2023-01-10 16:37 UTC, lgrd commented
@jmkerloch some tests (from itest, like those of pgrSource class) are not ready. I think I will comment them until I fix them.

2023-01-11 13:18 UTC, jmkerloch approved these changes

2023-01-11 13:27 UTC, merged